### ISSUE TITLE
Exagear Desktop release

### ISSUE THREAD

**Issue by twaik** [Eltechs/android-ubt#1]
Hi. Looks like eltechs.com is down for a long time and license ordering is fully stopped. Is there any chance for Exagear Desktop to be published as opensource software?

**Comment by khanhduytran0** [comment]
@pUnK2008 @maslovm

**Comment by ghost** [comment]
No bro, exagear is a non-open source project which is fully end , hopefully I got it with lisence key for all versions. I will start to improve it to make able to run gta 5 in 60fps in raspberry Pi 4

**Comment by SamarJi** [comment]
Sorry, gta 5 is enough powerful which can destroy exagear along with rpi .

**Comment by khanhduytran0** [comment]
I'm at least decompiled the Exagear Windows Emulator (java code) but can't get the X11 server to working.

**Comment by khanhduytran0** [comment]
Finding `com.exagear.axs.xserver` on Google I got a leaked code at https://www.linux.org.ru/forum/general/14957481
I tried search the same user posted and found he is also on 4PDA.

**Comment by ghost** [comment]
Javacode is great success , but without x11 it is like a emulator that can do anything expect emulating.

**Comment by ghost** [comment]
I was able to run exagear desktop through termux by anlinux, but there is gui .

**Comment by ghost** [comment]
I think that I can install it in userland

**Comment by ghost** [comment]
Today I will install xfce4 and exagear desktop , if it works , I will start it decompiling

**Comment by ghost** [comment]
If I got success , I will share it

**Comment by twaik** [comment]
Thanks.

**Comment by twaik** [comment]
I think for now the main problem is an x86 emulator. We can use any XServer present in Market or try to fix XWayland+TermuxX11 project. But it will be senceless without an x86 emulator.

**Comment by khanhduytran0** [comment]
> I think for now the main problem is an x86 emulator. We can use any XServer present in Market or try to fix XWayland+TermuxX11 project. But it will be senceless without an x86 emulator.

Or Xvnc since the current exagear is using Mesa instead of GLX indirect rendering (only if the Vnc client is good and fast).

**Comment by khanhduytran0** [comment]
> Javacode is great success , but without x11 it is like a emulator that can do anything expect emulating.
> 

It can only run in console mode.

**Comment by ghost** [comment]
I installed userland . Now I am installing xfce4 /debian. Now , I am trying to mount sdcard. Can anyone help me

**Comment by ghost** [comment]
Please check debian no root issue #54

**Comment by ghost** [comment]
And also anlinux app issue #236

**Comment by ghost** [comment]
I think I got some ways to mount sd card in userland

**Comment by twaik** [comment]
> It can only run in console mode

It runs binary code on host architecture. It does not matter GUI or console mode.

**Comment by khanhduytran0** [comment]
So it is "headless mode".

**Comment by ghost** [comment]
How can I get start-debian.sh (file of xfce4 of userland ) to edit in nano to mount sdcard

**Comment by ghost** [comment]
Sorry ,I checked the databases ,but there is no file from which I can mount sdcard,. But I find a alternate, but exagear doesn't install
Required operation need superuser permission error.

**Comment by ghost** [comment]
I was able to run exagear desktop

**Comment by twaik** [comment]
So?

**Comment by ghost** [comment]
I have lisence key, and xfce4 desktop in termux with ubuntu. I can decompile it but it will illegal. But I can x86 apps on armhf

**Comment by ghost** [comment]
How can I send screenshot

**Comment by twaik** [comment]
> I have lisence key, and xfce4 desktop 

Which version do you have?

**Comment by khanhduytran0** [comment]
> I can decompile it

How? 

> but it with illegal

But eltechs already gone...


> How can I send screenshot

Use github web in desktop mode.

**Comment by ghost** [comment]
It means if application is discontinued, anyone can edit it and launch in market without dev permission.

Thanks I will send the screenshot in which the architecture changes when exagear launched

**Comment by khanhduytran0** [comment]
> It means if application is discontinued, anyone can edit it and launch in market without dev permission.

I'm not sure, this is my thinking. But: **My decompiled Exagear Windows Emulator was existed on GitHub without any violation.**

**Comment by ghost** [comment]
I think nobody had complained and there is no dev who will complain

**Comment by ghost** [comment]
Here is my screenshot
![IMG-20200609-WA0014](https://user-images.githubusercontent.com/65938569/84164330-0559b880-aa90-11ea-8475-8707f9b74607.jpg)

**Comment by ghost** [comment]
Exagear works on terminal , but I am facing some problems while connecting to exporting display to vnc or xsdl

**Comment by SamarJi** [comment]
Can you help me

**Comment by SamarJi** [comment]
How's my internet speed

**Comment by khanhduytran0** [comment]
> Exagear works on terminal , but I am facing some problems while connecting to exporting display to vnc or xsdl

Same for me, network commands like `wget`, `apt`,... will give an error, only `ping localhost` will work.

**Comment by khanhduytran0** [comment]
You may check if `/dev` is mounted on Exagear guest rootfs.

**Comment by ghost** [comment]
I read may forums for how to export display from terminal to vnc viewer, from this termux commands doesn't worked. And anlinux's desktop environment also not worked. So, I am installing ubuntu-desktop from tasksel and I will export it through tightvnc server .

**Comment by ghost** [comment]
I think instead of exporting exagear on vnc , we can export ubuntu-desktop because there are many forums for this. But all the forums were for real ubuntu. I think it will work for me.

**Comment by ghost** [comment]
Src :- https://help.realvnc.com/hc/en-us/articles/360003474792-Why-does-VNC-Server-in-Virtual-Mode-on-Linux-appear-to-hang-show-a-gray-screen-or-not-start-at-all-#using-vnc-5-x-or-vnc-connect-6-0-6-1-or-on-a-different-version-of-linux--0-1

**Comment by ghost** [comment]
I got success , I run ubuntu default desktop
See on this screenshot:-
![IMG-20200610-WA0026](https://user-images.githubusercontent.com/65938569/84281522-5207c700-ab56-11ea-9dc0-7e4e22e24b32.jpg)

**Comment by ghost** [comment]
I need a video backend for it , or open gl es driver , how can I get it

**Comment by khanhduytran0** [comment]
> I need a video backend for it , or open gl es driver , how can I get it

You can't get any hardware accelerated.

**Comment by khanhduytran0** [comment]
You may try on @twaik's Wayland on Android, the Sparkle app to may get OpenGL ES.

**Comment by khanhduytran0** [comment]
Or use Mesa llvmpipe.

**Comment by ghost** [comment]
Thanks , it is also available on aptitude. I will install it . I have a problem while running freeciv from desktop, nothing happens but while running from terminal it gives this error
```
samar@localhost:~# freeciv
/usr/games/freeciv-gtk2: Fatal error: you're trying to run me as superuser!
Use a non-privileged account instead.
```
Please note this , samar is changed name of root

**Comment by khanhduytran0** [comment]
> ```
> Use a non-privileged account instead.
> ```

**Comment by ghost** [comment]
How

**Comment by ghost** [comment]
And also I had run lxde and xfce4 on termux and it took 5gb memory . But there is no issue regarding gui

**Comment by khanhduytran0** [comment]
Go to your account, may be your: `samar`.
Or create another user and login to.

**Comment by ghost** [comment]
Ok I have some screenshot of xfce 4 on termux , can I send it

**Comment by khanhduytran0** [comment]
Yes. May talking on another app? Like Discord?

**Comment by SamarJi** [comment]
These are the screenshot:-
![IMG-20200611-WA0013](https://user-images.githubusercontent.com/65938569/84488100-539fcf00-acbd-11ea-855c-105d3d124314.jpg)
![IMG-20200611-WA0012](https://user-images.githubusercontent.com/65938569/84488107-56022900-acbd-11ea-959a-589e93373c12.jpg)
![IMG-20200611-WA0007](https://user-images.githubusercontent.com/65938569/84488110-57335600-acbd-11ea-86d5-5d36f11f7690.jpg)
In first screenshot I set half of my device's native resolution ,everything is readable.

**Comment by khanhduytran0** [comment]
(but now I see that sending image without desktop mode is available in web)

**Comment by khanhduytran0** [comment]
The last one you didn't see anything?

**Comment by SamarJi** [comment]
Ok I will install discord

**Comment by khanhduytran0** [comment]
> The last one you didn't see anything?

Is terminal minimized or invisible?

**Comment by ghost** [comment]
It is minimized

**Comment by khanhduytran0** [comment]
Or you are talking on wallpaper changing on resolution?

**Comment by ghost** [comment]
No , when I killed vncserver and started next time , the resolution changed to default

**Comment by khanhduytran0** [comment]
Where did you started, by hand or .bashrc? Also are you using RealVNC or TightVNC/TigerVNC...?

**Comment by ghost** [comment]
Vnc4server

**Comment by SamarJi** [comment]
I am creating a guid as repo for it , just see it when it will ready

**Comment by SamarJi** [comment]
I installed discord

**Comment by SamarJi** [comment]
I also created server SynoGen

**Comment by SamarJi** [comment]
I installed discord
Please give me your name with tag. To add yourself

**Comment by SamarJi** [comment]
Discord is not a good application ,you should install telegram

**Comment by khanhduytran0** [comment]
> I installed discord
> Please give me your name with tag. To add yourself 

khanhduytran032#5558

> Discord is not a good application ,you should install telegram

Maybe, my device has very limited storage.

**Comment by SamarJi** [comment]
> Maybe, but my device has very limited storage.
**Telegram takes few storage and it is known for his speed and security.**

**Comment by SamarJi** [comment]
I had given request, just add me in discored

**Comment by SamarJi** [comment]
@twaik did you use discord, if yes , please give your name with tag . If no , just install it and give your name with tag.

**Comment by twaik** [comment]
My name in Discord is twaik. But I still think telegram is much better.

**Comment by SamarJi** [comment]
Yeah , I also

**Comment by SamarJi** [comment]
Because it provides cloud , secure and fast services

**Comment by SamarJi** [comment]
@twaik please give me your name with tag to give you friend request for discord

**Comment by twaik** [comment]
twaik#2234

**Comment by SamarJi** [comment]
@twaik thank, I had given request, just accept it

**Comment by twaik** [comment]
@khanhduytran0 @GxmerSam any updates?

**Comment by khanhduytran0** [comment]
@GxmerSam moved to Box86.

**Comment by ghost** [comment]
Hi there!, sorry for a late response, so I was trying to fix exagéar desktop debain-9 rootfs, it done but it works well for chroot not for proot. I got an another way to run wine-3.0eltechs by using box86, I tried to export BOX86_PATH as /opt/exagear/images/debian-9/usr/bin and BOX86_LOG is 2, hopefully it worked well. But still it have many errors related to lack of resources and proot.

**Comment by twaik** [comment]
Stale.
